version: '3.8'

services:
  web:
    build: ./
    command: ./entrypoint.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=consultation
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=asd
  frontend:
        build: ./cap-frontend/
        ports:
            - "5173:5173"

volumes:
  postgres_data:
