version: '3.8'

services:
  web:
    build: ./
    command: ./entrypoint.sh
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=consultation
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=asd
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redisdata:/data
  nginx:
    build: ./nginx/
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  redisdata:
  static_volume:
  media_volume:
